global:
  scrape_interval: 15s  # Récupérer les métriques toutes les 15 secondes

scrape_configs:
  - job_name: 'my-app'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
