CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" datetime NOT NULL,
  "updated_at" datetime NOT NULL
);

CREATE TABLE "tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "due_at" datetime NOT NULL,
  "priority" enum(low,medium,high) DEFAULT 'medium',
  "position" int NOT NULL,
  "status" enum(pending,in_progress,completed,cancelled) DEFAULT 'pending',
  "created_at" datetime NOT NULL,
  "updated_at" datetime NOT NULL,
  "owner_id" int
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "tasks_tags" (
  "task_id" int,
  "tag_id" int,
  PRIMARY KEY ("task_id", "tag_id")
);

ALTER TABLE "tasks" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "tasks_tags" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id");

ALTER TABLE "tasks_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");
