server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: symfony-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: symfony_logs # Label for the job
          __path__: /app/var/log/*.log # Path to Symfony logs inside the Promtail container 