controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Add this route definition for JWT login
api_login_check:
    path: /api/login_check
    methods: [POST]
