name: PHP CS Fixer

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHP CS Fixer (Fix)
        run: ./vendor/bin/php-cs-fixer fix src --config=.php-cs-fixer.dist.php || true

      - name: Run PHP CS Fixer (Check)
        run: ./vendor/bin/php-cs-fixer fix src --dry-run --diff --config=.php-cs-fixer.dist.php
